// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6fSKxysshtEM9mdop0Z1gRZdoCnGvDF4',
    appId: '1:1066000316254:web:536c239f9ce299f5aec1cf',
    messagingSenderId: '1066000316254',
    projectId: 'alzhelper-firebase',
    authDomain: 'alzhelper-firebase.firebaseapp.com',
    storageBucket: 'alzhelper-firebase.appspot.com',
    measurementId: 'G-GMTKM63JSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5XA1KN78x4CYGJjyaqbemSCKTe2CGR0',
    appId: '1:1066000316254:android:7b439f8160fc315aaec1cf',
    messagingSenderId: '1066000316254',
    projectId: 'alzhelper-firebase',
    storageBucket: 'alzhelper-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ4SeL1rRhhJKt26sV1gvrdDc-NWLCPms',
    appId: '1:1066000316254:ios:22955a8da7713b3faec1cf',
    messagingSenderId: '1066000316254',
    projectId: 'alzhelper-firebase',
    storageBucket: 'alzhelper-firebase.appspot.com',
    iosClientId: '1066000316254-j4ou093scvm9k709cgamgrlcel2b0rbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ4SeL1rRhhJKt26sV1gvrdDc-NWLCPms',
    appId: '1:1066000316254:ios:a8ddce8e34c8884daec1cf',
    messagingSenderId: '1066000316254',
    projectId: 'alzhelper-firebase',
    storageBucket: 'alzhelper-firebase.appspot.com',
    iosClientId: '1066000316254-nodrkuvt7p7kbrlb9pi6tlhpedultgmo.apps.googleusercontent.com',
    iosBundleId: 'AlzHelper-firebase-ios',
  );
}
